### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by paceholder** [chigraph/chigraph#73]
250 MB?  O_o

![image](https://cloud.githubusercontent.com/assets/322952/24334044/6a7e21f6-1263-11e7-9fbe-b60fd3020453.png)

**Comment by russelltg** [comment]
I accidentally checked in an appimage a bit ago, I'm looking  into rewiring some of that history to get it to be smaller. 

God, I'll never do that again.

**Comment by russelltg** [comment]
```bash
$ du -ch . -d 0 | sort -h
196M    .
196M    total
```
with a little bit of work. 

My dependencies are quite large as well--73M is dependencies and 30M is generated documentation.

**Comment by russelltg** [comment]
I'll close it, but come back if I think of a way to make it smaller.

**Comment by paceholder** [comment]
I'd better cut off a portion of old commits rather that rewriting the history

http://stackoverflow.com/questions/11687899/remove-cut-off-gits-revision-commit-history

And sorry... but why do you store the generated docs?

**Comment by russelltg** [comment]
It's easier for hosting on github pages--they either let you use a seperate gh-pages branch or just store your docs in the `docs` directory, which is much easier (I just set the doxygen output dir to docs)

I had to rewrite some history because I had to remove those files for all git history, deleting them would still keep them in the history.

My old commits aren't really that large although I'll look into it.
